### ISSUE TITLE
Feature Request: Drag and Drop Items into the Mook Generator

### ISSUE THREAD

**Issue by AnnoUltima** [crnormand/gurps#1019]
This would help with speed and convenience when creating NPCs. Allow us to drag and drop items to the Mook Generator screen, similar to the way that we can do so already after they have been created.

Thanks!

**Comment by crnormand** [comment]
Done.   With the character sheet re-organization that Nick did, this is now working (with no effort on my part, yeah!).   It will be in the next release.

**Comment by Farmeroz** [comment]
Is this only for dragging/dropping equipment, or could it be tweaked to enable dragging/dropping skills/ads/disads?

**Comment by crnormand** [comment]
Let me look into this.   It "should" be possible.

**Comment by crnormand** [comment]
Question... drag and drop items works in the NPC/Mini character sheet.   It does NOT work in the mook generator.   I was going to implement the drag and drop of skills/ads/attacks in the mook generator, not the NPC/Mini sheet.   This way a GM can drag skills/adds/etc. from existing characters, and they will fill in the mook generator fields with the appropriate information... but it will be up to the GM to tweak the final values.   

Is that what you were thinking?   I can't really drag them onto the NPC/Mini sheet, because the skill levels would not be correct (and you would have to switch to the editor to change them).

**Comment by Farmeroz** [comment]
Exactly what I was thinking, Chris.  That way you can use existing characters (PC or NPC) and grab things from them to throw on to a mook and all the basics are there.  Then you can tweak the levels/final values as needed.  Would be really handy.

**Comment by crnormand** [comment]
Done.   You can now drag and drop elements from a Full character sheet (not certain it if works with others) and drop it ANYWHERE on the Mook generator, and it will determine what it is and convert it to the "mook format".   Remember, you must drag the element (usually the name), not the roll.  If you drag the roll, it will paste the OTF formula in the notes section instead.

https://github.com/crnormand/gurps/pull/1128

**Comment by Farmeroz** [comment]
Awesome - thank you!
