### ISSUE TITLE
GURPS.performAction requires refactoring.

### ISSUE THREAD

**Issue by danielrab** [crnormand/gurps#1030]
While working on my module I am using GURPS.performAction a lot because it's the cleanest way to perform an action with a provided actor.
However, navigating it is pretty hard, and it's also not easy to figure out the requirements of each type of action at a glance.
I think the solution is to create a function for each type of action and have them being called depending on the type of action.
This would also allow scripts and modules to perform specific actions more easily, assuming the inner functions will be accessible in some way.
Also, the inner functions should probably return fuller data, and only GURPS.performAction itself should convert those into boolean results, that way a script calling an inner function would have direct access to the data instead of relying on hacks like looking at GURPS.LastTargetedRoll right after executing the action, which I am currently forced to do in my module.

**Comment by danielrab** [comment]
I am ready to help with the refactoring if you are currently busy working on other stuff

**Comment by mjeffw** [comment]
II'm totally with you. If you look at module/global-references.js you'll see my attempt to document fields in the Action to map them to the function that requires them. I was going to look into refactoring Action into an object hierarchy -- the top level would contain a stub with the action type and any global/universal fields (there may not even be any!) and an embedded object that contains only the fields needed for that type of action.

Ultimately I want to leave this decision to @crnormand since that function (and the project as a whole) is his.

**Comment by crnormand** [comment]
No.   Not going to do it...

j/k   ;-)
Of course it needs refactoring.     Especially if your modules needs/want to gain access to an individual action.  Let's do it.    For the record, I am never against refactoring... it is just that my tolerance for crappy code is WAY higher that Jeff's, which is why we are a good team.    I hack stuff together... and Jeff keeps reminding me to clean it up.

Let me describe the evolution of the code, and the requirements as I know them, and we can discuss plans.   @danielrab  if I am being too obvious, forgive me, I haven't worked with you yet, so I don't know your capabilities (although from the rumor mill, they are pretty good).

Any random piece of text can be sent to parselink() and it will return an "action object".    We hook into the chat log, the journal display and of course the character sheet.   The "action object" contains the HTML to display (which allows us to return a CSS laden string to simulate a button press) and the action data.    Originally, the action data was just a string representing the "action" (attribute roll, skill roll, etc.) and a few numbers (usually the target value).   This data is used by the performAction() function, which is just a huge IF statement tree.   Those two functions (parselink and performAction) are concretely tied together.    The string literals in parselink are used in the performAction IF check.

Of course, as we learned to parse more OtF formula, we added code in performAction() to execute the action that was parsed.

So you can understand how we go to here.    Both parselink and performAction are just huge IF statement trees that can easily be broken up.

NOTE:   The "HTML to display" that is returned by parselink also includes the action data encoded into the HTML.    See the functions gspan and gmspan at the bottom of parselink.js.     When a user clicks on the HTML (because it is displaying as an OtF button), and the encoded data is used to re-create the action (instead of trying to re-parse the text again).    You can see how it is used in gurps-wiring.js handleGurpsLink().    We needed to do this because the displayed test would have less information than the original text, and we needed to be able to record it.    If you examine any OtF formula in the browser, you will see something like:

`<span class="gurpslink" data-action="eyJvcmlnIjoiRFgxMyIsInNwYW50ZXh0IjoiRFggMTMiLCJ0eXBlIjoiYXR0cmlidXRlIiwiYXR0cmlidXRlIjoiRFgiLCJhdHRya2V5IjoiRFgiLCJuYW1lIjoiRFgiLCJwYXRoIjoiYXR0cmlidXRlcy5EWC52YWx1ZSIsImRlc2MiOiIxMyIsImJsaW5kcm9sbCI6ZmFsc2UsIm1lbGVlIjoiIn0=" data-otf="DX13">DX 13</span>`

Ok, what can we do going forward?   For the most part, each individual IF action.type === 'some action' in performAction() could be broken into its own method.     And instead of "falling" through to the final doRoll() call at the end of performAction(), each individual "perform action" method could call doRoll() directly (or whatever they need).   So it might look more like:

```
...
if (action.type === 'controlroll') return await performActionControlRoll(action)
if (action.type === 'roll' return await performActionRoll(action)

ui.notifications.warn('If you got to this line, the input action type was not recognized').
```
I don't feel that the action objects themselves have a lot of functionality... they are just two pieces of data... a display html and a structure containing enough information for the performAction function.    You are welcome to refactor them into an object hierarchy, but they have very little functionality on their own.    Just remember, there is a DIRECT tie between each section of parselink() and the corresponding IF statement in performAction().

Of course, if you are looking to call performAction() directly, without going through parselink(), then yes, you will need some kind of factory function to build the action data for you.   You can make an action object hierarchy to do this, or a series of factory methods.

WARNING:   The action.type === 'skill-spell' || action.type === 'attribute' portion of performAction() is a mess.   And of course, it is because it evolved over time.    Most of the work is done by processLinked() (which for some reason wasn't made into it isn't own method).   One of the biggest issues is that some of the variables set in processLinked() are "global" to the performAction() method, and not local to processLinked().   I think it is only 'target' and 'thing'.. but there could be more.

And of course, it got this way because of the whole "we kept adding cool things over time" issue ;-)     

**Plans going forward...** I would suggest (but do not insist on), doing it in steps (individual PRs) like:

1. Break out the individual IF sections of performAction into separate methods and remove the doRoll() call at the end (which means that each section will have to call doRoll() on its own, if necessary).   Originally, ALL of the functions called doRoll(), but over time we added things that did not (PDF links, Chat links, etc.)

2. Create factory methods for the action data which can be called by the various sections in parselink, AND by external modules like yours.    Basically, any time you see code like:
```
let action = {
      type: 'dragdrop',
        orig: str,
        link: m[1],
        id: m[2],
      }
```
This is a "factory" function to create the action data specific for that action.   

3.  Optional, if you want to make the action data into a first class object, do it now so you just modify the factory methods and the individual performAction functions.    You might find that once you have create the factory methods and broken out the corresponding performAction functions... you don't really need them... but YMMV.

Is this what you were thinking?

**Comment by danielrab** [comment]
yes, this is almost word for word what I was thinking about.  Thanks for a detailed description of how most things work there. I completely understand how such things come to be. The steps you are proposing sound very reasonable.

P.S.: there are rumors about my capabilities?

**Comment by crnormand** [comment]
LOL, yup!   And your module is proof!   I haven't had a chance to look at it yet, trying to catch up on my backlog... but I can tell that people like it.

**Comment by danielrab** [comment]
in the `attack` section there is this block
```js
if (!!t) {
      let a = (t + '').trim().split(' ')
      t = a[0]
      if (!!t) target = parseInt(t)
      if (isNaN(target)) target = 0
      // Can't roll against a non-integer
      else {
        a.shift()
        let m = a.join(' ')
        if (!!m) GURPS.ModifierBucket.addModifier(0, m) //  Level may have "*Costs xFP"
      }
    }
 ```
as far as I understand it deals with levels saved as strings, but levels are currently saved as integers, so as far as I understand it's almost fully redundant.

**Comment by crnormand** [comment]
That section was put in specifically for a player that embedded FP cost into the spell skill rolls, and it got expanded to attack skill level rolls as well.

So a user could enter their attack skill level as "12 *Costs 1FP", so that the attempt to use the attack would automatically deduct 1 FP from the character.

Of course, looking through the code right now, it seems that the "costs" feature was accidentally deleted from the skill check code at some point.   I am going to re-instate it, since I think it has some functionatility.

**Comment by crnormand** [comment]
My apologizes... it was not deleted...  it exists in the parselink.js code.

**Comment by crnormand** [comment]
And looking through the code some more... it seems that Attacks do the same thing (calculate possible COSTS in parselink.js... so is the section in performAction vestigial?   Quite possibly.   I think it should be safe to remove from performAction (since it is handled in parselink.js).

**Comment by Farmeroz** [comment]
Chris - the "12 *Costs 1FP" process doesn't appear to be working in the sample "cool macros" fireball Macro.  I mentioned this before but it was amongst my general issues with Macros not working but that's resolved but still FP isn't affected using the macro as written in your cool macro wiki (and similarly if I try to tag other resources - for example, I have a mage using Threshold magic and I want to increment that resources tracker when casting).

Any ideas?

**Comment by danielrab** [comment]
I am happy to say that I think I untangled the mess that was performAction, including the part of using skills and attributes. Now I am firmly in the "make the code repeat itself less" part of refactoring, so it shouldn't be long before I make a pull request.

**Comment by crnormand** [comment]
Cool!  I can't wait to see!

**Comment by danielrab** [comment]
there are different directions this could be taken now, and I have other things to do, and I already had problems merging changes, so I'll just make a pull request with the changes so far and we'll se from there.

**Comment by mjeffw** [comment]
Sounds good! Looking forward to reviewing code.
