### ISSUE TITLE
When changing Encumbrance Level and clicking on the word "Level", error below...

### ISSUE THREAD

**Issue by mehalforc** [crnormand/gurps#1052]
actor-sheet.js:1408 Uncaught (in promise) TypeError: Cannot read property 'current' of undefined
    at GurpsActorSheet._onClickEnc (actor-sheet.js:1408)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)

**Comment by crnormand** [comment]
It seems that you might have a damaged actor.   That line of code is iterating over the encumbrance values for the actor, and the only way the error can exist is if the encumbrance list doesn't exist at all, or has empty data in it (which should not happen, since this is created at actor creation and is NEVER deleted or edited).

The only way to fix this would be to re-import/re-create the actor.

**Comment by mjeffw** [comment]
Is this on a hosted (e.g., Forge) server, or self hosted? I had a problem earlier today with Forge where it timed out trying to download parts of the actor sheets. I can imagine this error being caused by a missing template.

**Comment by Farmeroz** [comment]
I just tested this (hosted on The Forge) without issue, using tabbed Sheet (I don't know if that makes a difference).  The Forge is currently having Cloudflare issues (time outs) trying to get to the bazaar/modules/etc., but game worlds seem fine.  Could be a caching issue, which I've seen before on The Forge, maybe?

**Comment by mehalforc** [comment]
I am self-hosting on local pc. It did it again... I updated and recreated the actor. (Same error.) Will download latest version of GGA and try again.

**Comment by crnormand** [comment]
Can you zip up your world and attach it?   I can't recreate it.

**Comment by mehalforc** [comment]
[gurps.zip](https://github.com/crnormand/gurps/files/7508262/gurps.zip)
I have two GM users with no passwords for them.
