### ISSUE TITLE
Query: How to add a sound to go with an anim?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1153]
I might be going crazy, but I thought this was shown somewhere - a video or a document - but I can't find it?

**Comment by Farmeroz** [comment]
Found it!

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-6e703132-7fff-7b0f-9752-7df6cd56903b"><div dir="ltr" style="margin-left:0pt;" align="left">

/sound <filename>/sound w0.5 <filename>/sound v2 <filename>/sound w0.5 v2 <filename> | Play a sound.  The filename must be the full path to the sound.  If the ‘w’ parameter is present, wait that many seconds before starting the sound (useful for timing the sound with an animation).   If the ‘v’ parameter is present, set the volume level.
-- | --


</div></b>
</body>
</html>

**Comment by crnormand** [comment]
If you are adding an animation and sound to an attack (or skill check), you can create a single command (using the double \\). 

I recommend calling the /sound command first, giving it a "wait" time so that it will delay until the animation is playing the correct section.  

/sound <file> w0.75 \\ /anim <file>
