### ISSUE TITLE
Support setting current maneuver somehow

### ISSUE THREAD

**Issue by xdy** [crnormand/gurps#122]
This would be handy both because some maneuvers add modifiers (e.g. Do Nothing), and to remind oneself and others that the character may or may not do certain things due to the last selected maneuver.

I did two quick POCs, the first one I did it by adding a dropdown on the combat character sheet with a list of maneuvers to choose from, that added effects using the currently available methods on modifiers.js. This way I could only add temporary modifiers however, which doesn't really work well for this. (Or, of course, I could change the api. But, to make this work I think I'd have to rework how modifiers work a fair amount. So, too much friction for now at least.)
If this POC is continued the dropdown (or some equivalent ui component) would have to be added to all sheets, and, most likely a graphic representation of what the current maneuver is would have to be added. Like, a status. Which led me to the second POC.

Which was to add the maneuvers as statuses. This way I could use - or possibly misuse :) - the existing support for statuses. And, as maneuvers are kinda sorta statuses (as well as being actions...) it didn't fit too badly. I stopped after I had successfully added two maneuvers - with really badly chosen state icons :)
If the second POC is continued a way to separate the statuses from the maneuvers would be needed (presumably by hooking into the display of the status icon selection menu). Suitable icons can most likely be found on game-icons.net

This feels like it's far enough on the 'no automation' side of the fence for sjgames to not have a problem with it. (Though, I admit that I'd like for Maneuvers to be a first class concept of it's own, setting limits to movements, etc. But, might be a bridge too far.)

Anyway, I'm attaching the two POCs as patches (zipped as github issues don't allow .patch files for some reason) in case you might find them useful starts.

[gurps_maneuvers_poc_1,_dropdown___temporary_modifier.zip](https://github.com/crnormand/gurps/files/5716028/gurps_maneuvers_poc_1._dropdown___temporary_modifier.zip)
[gurps_maneuvers_poc_2,_statuses.zip](https://github.com/crnormand/gurps/files/5716029/gurps_maneuvers_poc_2._statuses.zip)

**Comment by crnormand** [comment]
Wow, you are brave looking through my crappy code.   Modifiers.js was one of the first JS files that I created (outside of the Simple World building files), and I was just learning Javascript.   Looking back, it is all hack.   But hey, I was trying to get functionality out the door.

We have plans (on our to do list) to expand on the number of "statuses" that can be applied to a token.   And I agree, a "maneuver" is a kind of status.   It is a reminder to the player (and GM) of the "status" of their character.    I also agree that a Maneuver should be a first class object... in the hopes that someday SJG will let us expand on that (Mook would really love to be able to limit a token's movement).   As for how it is triggered, I am open to suggestions.   A pulldown menu on the GUI, a separate "maneuvers" dialog, etc.   The issue here is what maneuvers to include.   I feel this would have to be a GM configurable item because not all GMs want to play with all maneuvers.    Over time, we built up our list of maneuvers, and created this cheatsheet:   https://docs.google.com/document/d/1IyN2C1jlfu9UehfdumFXSy_SesaV-_Cl0YczlVJKTgE/edit?usp=sharing and it is a big thing.

The first step is creating the status effect and making it look different from other kinds of statuses so the user can know that it is a maneuver.   My first thought is a specific color scheme (that way we won't have to hack into Foundry's status effect code).   Most of the current status effect icons all came from game-icons.net.   I had to stretch to fit some of them, but so long as the picture is different, people can get used to it (especially "sitting").

Once we have a maneuver status, then at least players can manually set and unset their maneuvers as reminders.

Currently, our effects are all static.   I have not tied into the "active effects" logic yet.   The only thing that I wanted to hook into was "duration", so an effect (or a maneuver) would only last a certain amount of time (or rounds).   But this is one of those levels of automation that I want to get permission for.  

Let me ponder further and discuss with Nick/Jeff.

Oh, and thanks for the interest!

**Comment by xdy** [comment]
Heh. Looking at *my* early code on https://github.com/xdy/twodsix-foundryvtt is painful enough I can handle anything.  :)
I'm a backend developer - mainly java the last couple decades, with some sysadmin/dba/etc - so, javascript/web development just feels *weird*. Though I mitigated some of it by using Typescript for my system, it feels a *lot* more comfortable to me. I don't mind the need for transpiling to javascript, feels just like home - e.g. java - :)

As for maneuvers, yeah, I agree that they should be configurable. (For the first POC I actually started with maneuvers as items (twodsix is reasonably heavily item-based so it felt natural), but I backed that out early as it seems you don't really do much with items. And, of course, the source of the rows in the dropdown doesn't really matter this early.)

Color scheme should work nice, that would indeed remove the work of adding a hook (or monkey patching).

Thank you for making a good Gurps system!
And, for setting it up import-first. I *almost* did it that way with Twodsix (https://github.com/xdy/twodsix-foundryvtt/issues/3) and am kind of regretting not doing so.

**Comment by crnormand** [comment]
Funny, I am a 25 year java dev myself (started with v0.9 beta).  Mostly backend, high availability stuff.   No web development AT ALL.   Jeff is also a 20+(?) year java dev, but his experience is more broad than mine.  

And you are welcome.  Jeff and I love GURPS (he is the GM of my group) and we really wanted to make this thing work.

**Comment by mjeffw** [comment]
Yeah, I was Java 1.1 certified in...1997?

**Comment by xdy** [comment]
99 for me I think, at least I got a consulting gig at a bank that required all consultants to be Java certified in mid 99.

Hmm. I wonder if working in IT is a good predictor of liking Gurps. At least it works for the last group I played Gurps with.
Other than me it consisted of a java developer/hardcore Java evangelist, a Sun/Oracle employee, two sysadmins, one tester, and, the odd one out, an emergency room nurse. :)

**Comment by mjeffw** [comment]
If you have a moment, I would like to hear how you integrated TypeScript into your Foundry VTT development. I'd like to do that but haven't had the time. If you do, let's move the convo to email: geek.macbeer@gmail.com.

**Comment by xdy** [comment]
Sure thing. Rambling mail incoming. :)

**Comment by khamulbr** [comment]
I'm a Java guy to (since 97), from that time I've been mostly working with Java (front and backend) and more recently with JS (front and backend too)!

 I'm using this awesome Game System with my brave group of GURPS players and we're having a lot of fun! 

I hope to help you guys in anything that you think it would be feasible.

Cheers from Brazil!

**Comment by trev-dev** [comment]
+1 for using TypeScript. I feel like the project could benefit from separating source code from a neatly webpacked bundle. Would be a great excuse to break down the modules into separate files and organize/consolidate modular aspects of the codebase. We could also then use SCSS or postCSS to reason about our styles better and pack those in a production bundle as well.

**Comment by trev-dev** [comment]
Additionally with an npm based dev environment we could leverage the thousands of packages that exist.

Packages like https://www.npmjs.com/package/xml2json

Or not, we can keep the dependency bloat down, too ;)

**Comment by mjeffw** [comment]
@xdy @khamulbr @trev-dev 
I started working on this. I'll attach some screen shots and images.

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/118877710-c3024380-b8bc-11eb-9e15-5869c1878262.jpeg)

**Comment by mjeffw** [comment]
Here's some ugly ass icons I free-handed using GIMP:

![image](https://user-images.githubusercontent.com/7349413/118879265-7fa8d480-b8be-11eb-8f50-c7a878be779b.jpeg)

**Comment by trev-dev** [comment]
@mjeffw I'm still able to reach out to the artist of our existing icons if you would prefer that they make them. These don't honestly look half bad though...if they were done in Inkscape you could smooth out those edges by manipulating nodes instead of freehanding.

**Comment by mjeffw** [comment]
How I expect this to work:

Normally, there is no maneuver selected outside of combat. For simplicity, I may default it to "Do Nothing" (instead of making it blank). No status icon will be displayed in the Token HUD.

When combat starts or when a token is added during combat, it will automatically set the maneuver to "Do Nothing" and display the status icon in the HUD. There will probably be no restrictions on changing the maneuver other than by actor/token ownership.

When the token is selected, any restrictions on move or defenses will be displayed in the modifier bucket window. These are informational only and will not prevent a player from doing something illegal, such as taking his full move while doing a Wait maneuver. Any bonuses associated with the maneuver will also be displayed in the bucket window.

At the end of combat, the maneuver will default back to 'Do Nothing' and the icon cleared from his HUD.

What do you think? What am I missing?

**Comment by mjeffw** [comment]
> @mjeffw I'm still able to reach out to the artist of our existing icons if you would prefer that they make them. These don't honestly look half bad though...if they were done in Inkscape you could smooth out those edges by manipulating nodes instead of freehanding.

Yeah, my weird educational background is showing a bit. I have MS in Software Engineering + a BS in Computer Science, but my undergraduate minor was Fine Arts. I did drawing, oil painting, and glassblowing as part of my BS degree.

I would like a real artist to do these icons! We can offer then a commission of 10% of the total sales of the game aid. ;-)

**Comment by trev-dev** [comment]
@mjeffw I'll send the email before the end of my day :)
