### ISSUE TITLE
OtF's can evaluate success level

### ISSUE THREAD

**Issue by Battenhatch** [crnormand/gurps#1281]
As asked on Discord: Things like Physicians care have differing results given the level of success of a skill roll. Physicians care give cs: +2/os: +1/of; +0/cf: -1 HP. It would be nice if OtF capability could be expanded to accomodate such results.

**Comment by crnormand** [comment]
Perfect, thank you.

As I mentioned in Discord, it might be easiest to expand the enhanced IF syntax. 

Basic: /if [otf] [otf] /else [otf]

Which works for 80-90 of the cases.  However, if you need to do something more complex, like embedding an IF check inside of an IF check, we couldn't parse it.   

Advanced: /if [otf] {chat commands} {"else" chat commands}

I think we can enhance the parser to look for leading "+" and "-" (or something that indicates a crit-pass and a crit-fail).

**Comment by crnormand** [comment]
Ex:

/if [Sk:Phys] +{/hp +2} {/hp +1} -{/go -1}

The fail clause is always the second {} clause.  So if you just need that, you would use:

/if ! [Sk:Phys] {fail clause}

I'm not certain how crits would work with an "if not" clause:  

Would +{} be triggered when it is a crit-fail?   Yeah, I guess so.

**Comment by mjeffw** [comment]
I'm lost. How would `/if [Sk:Phys] +{/hp +2} {/hp +1} -{/hp -1}` work for an ordinary failure? Are you suggesting `/if [Sk:Phys] +{/hp +2} {/hp +1} {/hp +0} -{/hp -1}` (i.e., no difference between success or failure except position?) I don't know if I like that. I think this is going to be hard to read and write.

I'd rather be explicit with something like `/if [Sk:Phys] cs:{/hp +2} s:{/hp +1} f:{/hp +0} cf:{/hp -1}`. Then you could put whatever terms you want in whatever order you want.

**Comment by mjeffw** [comment]
Maybe this is some enhanced version of `/if`. Maybe a `/check` command?

`/check [Sk:Phys] cs:{/hp +2} s:{/hp +1} f:{/hp +0} cf:{/hp -1}`

**Comment by crnormand** [comment]
I would like to keep it as an enhanced version of IF, if possible.   And yes, currently both the basic and advanced syntaxes are position dependent.   It isn't a big deal, when just dealing with 2.   Most usages have been "if [something] [do something]".   The "/else" parameter came later.

And then, as mentioned, the `{}` syntax appeared so we could handle multiple recursions of IF statements.  So I feel that we still need to allow the positional IF statements:

`/if [otf] {pass} {fail}`

But we could also enhance the parsing to also allow something like:

`/if [otf] +{pass} -{fail}`
`/if [otf] ++{crit-pass} +{pass} -{fail} --{crit-fail}`
`/if [otf] cs:{/hp +2} s:{/hp +1} f:{/hp +0} cf:{/hp -1}`

But since we will still have the positional logic in (for backwards compatibility), we should also be able to support something like:
`/if [otf] ++{crit-pass} {pass} {fail} --{crit-fail}`
`/if [otf] cs:{/hp +2} {/hp +1} {/hp +0} cf:{/hp -1}`

And yeah, I think I agree that we should NOT allow `!`.   I can't seem to wrap my head around what it would actually mean ;-)

**Comment by mjeffw** [comment]
I maintain it's not an if statement anymore. It's more like a switch or pattern matching.

**Comment by crnormand** [comment]
I understand your point... but I also think that if we leave it as an enhancement to an `/IF `statement, a user could take an already existing `/IF `check, and just add new consequences for crit-pass/fail.

And as far as use cases go, I don't know how many people are looking for a switch statement for outcomes... as evidenced by the fact that this is the first request for such.    IMHO, critical success/failure are usually handled by the GM.   As far as I know (and agreed, I am not a RAW rules lawyer), there aren't a lot of places in the Basic Set where they do provide outcomes for critical successes/failures.   There are some, sprinkled throughout, but it isn't a requirement for every skill test.

So I don't see what value we gain by making a new chat command.    Agreed, in this new case, we are no longer dealing with a boolean, we are dealing with a 4 state variable (crit-pass, pass, fail, crit-fail), but in "every day" usage, one could say:

if crit-pass then do-crit-pass
else if pass then do pass
else if crit-fail do crit-fail
else do fail

And most everyone would understand that.   I don't think there will be a lot of confusion with the added `IF `syntax.

**Comment by Farmeroz** [comment]
Crit results would be great.  Crit hits could automatically bring up crit tables, for example (user specified to cater for whatever a user has named them).  There are a number of cinematic effects in MA, for example, where a crit has an effect.  When spell casting, crit means no energy cost, for example.  A crit failure on certain skills triggers a verification (Malf checks for firearms, piloting, and others).

Couple with this would be a previous request to enable users to define crit ranges (some house rules allows a crit on a 7 for an effective skill of 20, for example).  Also, allowing checks for crit could allow sounds or animations being triggered?

**Comment by mjeffw** [comment]
> And as far as use cases go, I don't know how many people are looking for a switch statement for outcomes... as evidenced by the fact that this is the first request for such.

I wasn't asking for a switch statement. I suggested a command fit-for-purpose: A /check command, which makes so much sense that I can't see doing anything else. The only time one would want to look for crit success or critical failure is when rolling a check against a skill or attribute. Provide that command. Just my not-so humble opinion.

**Comment by crnormand** [comment]
So basically we agree on the functionality, and are just discussing what to call it?  :-) Ok, I am fine with creating a new command called /check.
However, I would like to point out that if we also build in a "margin of success" feature... we probably will want to add that to the /if command as well.   So these two statements would behave basically the same way:

```
/check [otf] s:{/hp +@margin} f:{/hp -@margin} 
/if [otf] {/hp +@margin} {/hp -@margin} 
```

Which is why I was arguing for the overloading of the /if statement.   Yes, I agree it is not completely consistent, but I felt that it would not be confusing.   And then it wouldn't be hard to add critical success and critical failure options to the /if parsing.  In which case, these two command would be equivalent:

```
/check [otf] cs:{/hp +@margin} s:{/hp +1} f:{/hp -1} cf:{/hp -@margin} 
/if [otf] cs:{/hp +@margin} {/hp +1} {/hp -1} cf:{/hp -@margin} 
```

And I wouldn't mind adding the s:{} and f:{} formatting options to the /IF statement (optional, of course... we need to remain backwards compatible).  So we would be able to support:
```
/if [otf] cs:{/hp +@margin} s:{/hp +1} f:{/hp -1} cf:{/hp -@margin} 
```

Also, this just hit me as I was reviewing this post... the /check command would have to implement the recursive call functioning of the /if statement, so the user could put more /check (or /if) commands inside any one of those brackets.
```
/check [otf] cs:{/if [IQ] {/hp reset} {/hp +@margin}} s:{/hp +1} f:{/hp -1} cf:{/hp -@margin} 
```

It seems to me that the /if and /check functions share so much functionality, why not just have one command (overloaded)?   

That has been my thought process.

**Comment by mjeffw** [comment]
I agree; if you're going to enhance the if statement anyway, ignore everything I've been saying. We don't need two commands that do the same thing. I don't like the enhanced if-statement, but that's me.

**Comment by crnormand** [comment]
https://github.com/crnormand/gurps/pull/1284
