### ISSUE TITLE
Drag n' drop equipaments

### ISSUE THREAD

**Issue by yashirobr1** [crnormand/gurps#1350]
Hello, I currently use the GURPS GAME AID 4TH module on the Foundry VTT, and a situation happened yesterday at my table, one of the players was incapacitated, and his companion wanted to take his sword for himself in combat, but I didn't see a way to transfer the item from one sheet to another, so that I have the right skill level and damage too, any solution?

It can be through some module, macro or formula

**Comment by crnormand** [comment]
The only solution at the moment is to create their sword as a Foundry Item: https://www.youtube.com/watch?v=cOU78-RvXdc
Foundry Items can be dragged and dropped between players.     Otherwise, you would need build it in GCA/GCS and re-import.

This is a well known, and long standing issue.   So I am going to close this.
