### ISSUE TITLE
Mook Generator does not parse resistance based attacks

### ISSUE THREAD

**Issue by Kirzai** [crnormand/gurps#137]
E.g. a Bodak death gaze from this page:
http://gurpswiki.wikidot.com/m:bodak

Here is the attack text from that page:
Punch (14): 1d crushing. Reach C.
Death Gaze (Resisted by HT): Kills target instantly. Vision-based attack. Range 10.

**Comment by crnormand** [comment]
Unfortunately,  it won't be possible to parse every variation on a stat block.   As of the upcoming release (v0.8.4), melee and ranged attacks are recognized if they follow 1 of 2 patterns:

Name (Skill #) damage-formula optional-attributes
Name (Skill Text) "damage text" optional-attributes

The "Punch" attack follows the first pattern, but the "Death Gaze" attack doesn't follow either.    Since it isn't recognized as an attack (but it seems to be in the attack section), it is added a comment (a line starting with #):
![image](https://user-images.githubusercontent.com/8931036/103498418-b18b3400-4e12-11eb-9a70-fbfa23e32a4a.png)

You can add it as a ranged attack with a little editing.   First, cut the line from the Melee section, and add it to the Ranged section, removing the leading #.    If you press TEST MOOK, it will show:
![image](https://user-images.githubusercontent.com/8931036/103498483-f31bdf00-4e12-11eb-8377-c487050a6f1b.png)

Indicating that it cannot match either pattern.   Since this attack doesn't use a Skill roll or a Damage roll, you must indicate the damage by enclosing it in quotes.    Once you make the change and press TEST MOOK again, it will show:
![image](https://user-images.githubusercontent.com/8931036/103498811-fd8aa880-4e13-11eb-805d-263c678668b4.png)

Indicating that "Vision-based attack." is not one of the recognized optional attributes of a ranged attack such as "range", "acc", etc. (the complete list is [here](https://docs.google.com/document/d/1NMBPt9KhA9aGG1_kZxyk8ncuOKhz9Z6o7vPS8JcjdWc/edit#heading=h.9v4q31dhumxu)), 

Since "Vision-based attack." is just a comment, move that to the next line, with a preceding # to indicate that it is a comment and test again:

![image](https://user-images.githubusercontent.com/8931036/103499126-05971800-4e15-11eb-8dc8-ef8fd05db24f.png)

Which does not produce an error.   If you create the mook, and look at it using the Full Sheet, it will look like:

![image](https://user-images.githubusercontent.com/8931036/103499172-2cede500-4e15-11eb-8575-9851d755134a.png)
