### ISSUE TITLE
[Feature Request] Sticky modifiers, modifier types and multiple buckets

### ISSUE THREAD

**Issue by Gloogirl** [crnormand/gurps#1506]
As the name suggests these are actually three different requests.

**Multiple buckets**

Allowing several modifier buckets that can be toggled active or inactive, or called for separately, allowing you to have a bucket for a specific purpose that you can call for.

**Modifier types**

A way to differentiate various modifiers so they're only used for specific types of rolls. +2 to damage rolling and clearing only when you've made a damage roll, +2 to attacks rolling and clearing only when you've made an attack, etc. This would be especially good for the final feature.

**Sticky modifiers**

Like the bucket toggle that keeps the modifiers you could instead put in a specific modifier that will stick. If combined with modifier types this could be helpful in something like a fight with bad footing, or poor lighting.

**Comment by devakm** [comment]
This is a great idea! I love it!

**Comment by crnormand** [comment]
Some of this can be partially accomplished by dragging and dropping the modifier bucket into a macro slot (or a Journal entry, or anyplace on a character sheet).   That will save the current bucket, and re-apply it anytime the macro button (or OTF button) is clicked.

We have looked into "modifier types"... but hit a snag...  if you have a bunch of modifiers "waiting"... like +2 Aim, and +2 flame damage on an arrow, and -2 IQ/DX rolls due to shock... how do we display all of these modifiers, such that the user knows when they will be applied?   We felt that it would be worse to automatically apply a modifier (and used it up) in an incorrect place, then to require the user to explicitly set the modifiers for the next upcoming roll.

The same goes for a "sticky" modifier.    During such a combat, the GM may ask each player to roll a D6 (to see who gets hit next)... and you wouldn't want the "sticky" modifier to apply to that roll.    Sticky modifiers are only really good on multiple rolls in a close proximity of each other (like rolling PER for all of the nearby NPCs).   Currently the modifier bucket does have the "magnet" icon on it, which turns on "sticky"... so if you are making a bunch of rolls using the same modifiers, you can use that. 
For other rolls, this can marginally be accomplished by building the "sticky" bucket and dragging and dropping onto the macrobar.   Also, the GM can build the modifier bucket (with the appropriate modifiers) and "send" it to the player (especially good with new players).

And finally, automatically applying modifiers is starting to cross the line into 'automation'... and we are still discussing this with SJG.   So long as we require the User or GM to apply the modifiers themselves... we aren't "playing the game" for them.   Who knows, we may be able to offer this in the future.. but for now.  We cannot.

**Comment by devakm** [comment]
> We have looked into "modifier types"... but hit a snag... if you have a bunch of modifiers "waiting"... like +2 Aim, and +2 flame damage on an arrow, and -2 IQ/DX rolls due to shock... how do we display all of these modifiers, such that the user knows when they will be applied? We felt that it would be worse to automatically apply a modifier (and used it up) in an incorrect place, then to require the user to explicitly set the modifiers for the next upcoming roll.

This is fine for default behavior, but the there should at least be an option you can pick for the bucket to treat it in a "sticky" fashion. This would allow a custom macro for an attack to take advantage of several modifiers the user has picked (or the GM has provided). As it stands now, the modifiers have to be baked into the macro itself or they will be ignored.

To be clear, we are not asking for GGA to automate this itself, just to provide support for GMs who may want to create custom features for personal use.

**Comment by devakm** [comment]
Sure! Let's say I create an OtF like this:
`["Rapier Slash"/if [A:Rapier*Swing*] {!/anim Rapier01_06_Regular_White *0.3 -0.4 +2 \\/r [D:Rapier*Swing*]}]`
If I use the modifier bucket to picky Mighty Blow `[+2 damage (Mighty Blow) *Cost 1FP]` before using the above attack OtF, then the modifier is uselessly consumed during the initial attack roll '/if [A:Rapier*Swing*]' clause instead of when I roll damage during the `/r [D:Rapier*Swing*]`
Does this make sense?

**Comment by Gloogirl** [comment]
I think that either option has issues. Not being able to show all the modifiers is certainly a snag (though hovering over the modifiers and getting them all to display would be an in-between). But as devakm mentioned having it apply indiscriminately has its own hiccups. Ideally I want **both** to be available, so you can play with or without modifier types.

Though the above message doesn't really display what I wanted. Sticky modifiers would be ones that stick around after use, so regardless of type they'd stay unless you toggled the sticky off, just like the sticky bucket works now but per modifier.

What Devakm talks about is more the modifier type from my examples, where it checks "is this the right type of roll" before it uses the modifier.
