### ISSUE TITLE
Actor Permissions & Actor Biographies

### ISSUE THREAD

**Issue by Hubok** [crnormand/gurps#154]
I'm putting in an issue request for the one main feature that's preventing me from using this system right now. I'm rolling these two suggestions together because there's some overlap. In my game, we like to have a list of characters that people have met and they can scroll through some basic info on them. Keeping these tied into the actor list reduces the amount of clutter, instead of needing separate journal entries as well. 

For the bio part, I would like to suggest this:
Surround the current character sheet in a wrapper and add navigation. One option for the biography (default), and the other the character sheet. The biography would just display a page, and then it can be edited by the owner/GM with a basic WYSIWYG editor. Below this, a basic GM note section may be nice as well.

The permissions part plays into this. My proposal is below for the permission levels:
- None: Actor doesn't exist for the user.
- Limited: Actor shows up, and the bio is visible to the user.
- Observer: Actor bio **and** the character sheet shows up, but is read-only.
- Owner: Same as observer, with edit permissions.

**Comment by mjeffw** [comment]
Can you help me visualize this better? Maybe with an example? I don’t get what you mean by a “wrapper”.

**Comment by crnormand** [comment]
FYI, there is already a module that adds GM notes (and it works with our code):   https://foundryvtt.com/packages/gm-notes/

As for the feature, this may take some doing.   I really don't want to muck up our already mucked-up HTML, which means that the best way to display the biology would be to create a separate sheet for it, but Foundry only supports a single sheet per actor.

**Comment by Hubok** [comment]
> Can you help me visualize this better? Maybe with an example? I don’t get what you mean by a “wrapper”, or navigation.
> 
> Edit: Oh, do you mean a tabbed interface, to switch between bio and sheet view?

Yeah, tabbed interface, see below.

![](https://i.imgur.com/H0YQuir.jpg)
![](https://i.imgur.com/o9hgwNS.jpg)


> FYI, there is already a module that adds GM notes (and it works with our code): https://foundryvtt.com/packages/gm-notes/
> 
> As for the feature, this may take some doing. I really don't want to muck up our already mucked-up HTML, which means that the best way to display the biology would be to create a separate sheet for it, but Foundry only supports a single sheet per actor.
> 
> Edit: LOL, I guess Jeff and I were editing at the same time. ;-)

I hope the example above is reasonable, as this kind of thing does reduce the clutter dramatically.

**Comment by crnormand** [comment]
I am loath to duplicate the functionality of the already existing module.   GM Notes works with our code (and many others) and seems to provide some of the functionality that you request.  https://foundryvtt.com/packages/gm-notes/    It allows you to enter GM Notes on individual character sheets and Journal entries.

So that leaves the "public biography" / "private charactersheet" tab feature.      At the moment, I don't want to muck up our already convoluted HTML/CSS.   It seems that the functionality you are asking for can be accomplished using Journal Entries and the GM Notes module.   Journal Entries already have the permissions functionality (where you can set which play can see which entry).

I understand that this requires that you maintain 2 lists of NPCs... the "secret" list in Journal Entries and the "public" list in Actors.   So for that reason, I will leave this request open.

**Comment by Hubok** [comment]
I understand that the biographies would take a bit, but I would at least like to request permissions to be working so we can at least display a character's name and picture but not their entire private sheet.

**Comment by crnormand** [comment]
Closing.   Limited ownership just displays the bio portion of the character sheet
