### ISSUE TITLE
Modifier Bucket Selected Character Remains Selected even when token is de-selected

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#164]
As title. Even when a token is deselected, it remains as the active token in the bucket.

**Comment by crnormand** [comment]
I've implemented the following process:
When a token is selected or a character sheet is opened (or gains focus), set the LastActor.
If a token is deselected, or a character sheet is closed, and the actor that it represents is saved in the LastActor, the LastActor is cleared.

All good, so far.   However, if the user clicks on a character sheet TITLE BAR, there is no event.   It hasn't gotten focus.   Which means the user may "think" they have selected a certain character (by clicking or double clicking or even dragging the sheet around by the title bar), but internally, we don't know about it.  The LastActor is still empty.

If the user clicks IN the character sheet, ANYWHERE, it will gain focus.

So that is the problem.  A GM could have 2 character sheets open, close the top one, and drag the second one around and even double click on the title bar to collapse it, and they try to execute some On-the-Fly formula such as [ST+2], and our code will report "You must have a character selected", even through the user can plainly see that a character sheet is open.

@Legendsmith 🔨 (TCDG) [UTC+10] Any ideas how I can listen for events that affect the titlebar?   This is "web magic" that I just don't know.

**Comment by crnormand** [comment]
Stas (in sys-dev) figured it out:
html.parent(".window-content").siblings(".window-header").click(ev => { this._onfocus(ev) });

I will push my changes and close this issue.
