### ISSUE TITLE
VTT Notes

### ISSUE THREAD

**Issue by ArminSykes** [crnormand/gurps#1667]
I'd like to update the exporter to include VTTNotes for the traits. I'm not sure of your structure, so I'm not sure how that should be included. 

Right now, you have UserNotes going into a string element labeled 'text'. I expect VTTNotes should also go in there, but I don't want to remove UserNotes because that may also remove non-VTTNotes that users actually want in there.

What would be the correct way to concatenate these two different fields to include them both in the 'text' element? Just concatenate them with a line break between them maybe? UserNotes-LF-VTTNotes? Or is there a better field?

**Comment by crnormand** [comment]
Actually, concatenating them would work great.   That is exactly what we do with the GCS vtt_notes during import.   Our internal character model does not have a separate attribute for vtt_notes.     

It sole purpose was to allow users to enter text that is NOT normally displayed on the normal character sheet (e.g. On the Fly formulas).   Of course, other VTTs might want to use it for something else... but since we got here first ;-)

**Comment by ArminSykes** [comment]
Thanks. I'll see about doing that shortly.
