### ISSUE TITLE
Issue with "On-the-Fly" formulas

### ISSUE THREAD

**Issue by Sojourner756** [crnormand/gurps#1827]
After discussing an issue at length in GURPS discord with Nick Coffin, PI we are able to narrow down a problem and its likely cause.

While using an on the fly formula /r ["(Vision roll at ‑10 or Per-based Traps roll at ‑5)" Vision -10 | S:Traps-5 (Based:Per)] I would get nothing returning with a character selected and need to select character if one wasn't. The issue was found that if you were required to roll any roll that was modified to or below 0 it wouldn't make a roll at all. 

I would like to be able to use "On-the-Fly" formulas without thought or consideration. It is an excellent feature that will make playing GURPS for even new players fast and easy even when not using rules lite options, and returning something when a roll is invalid would be useful in avoiding confusion.

**Comment by Sojourner756** [comment]
For ease of reference, when the GM allows a roll, "... a roll of 3 or 4 is always a success" and "You may not attempt a success roll if your effective skill is less than 3 unless you are attempting a defense roll" and "A roll of 3 or 4 is always a critical success" page 347 of basic set

**Comment by Sojourner756** [comment]
So I would suggest a pop-up that says "Cannot roll, skill insufficient" and allow a roll for defense rolls.

**Comment by crnormand** [comment]
Which version of Foundry are you using, and which version of the GGA?

**Comment by mjeffw** [comment]
@crnormand I found this problem in both Foundry v10 & GGA 0.15.x, as well as Foundry v11 & GGA 0.16.x.

The problem occurs in the chat command handler that takes a list of checks such as `[Vision -10 | Traps]`. To resolve this, it gets the target of each of the rolls and selects the one with the highest value. Unfortunately, that code also uses the value of "0" to represent a skill that isn't found. So in the example above ("[Vision -10 | Traps]"), if the character does not have Traps, and his Vision score is 10 or less, the code ends up with no targets of 1 or higher, and just quietly quits.

I propose that instead of quietly stopping, we put up a message that says "No skills were found, or target rolls are less than 1" or something.

**Comment by crnormand** [comment]
Ah yes...   would:
`"This character does not have a viable skill (effective level 3 or higher) that can be rolled"`
work?
