### ISSUE TITLE
[Feature Request] Corrosive Damage and Ablative DR

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#191]
When receiving corrosive damage or having ablative DR, track damage to DR as a type of resource.

**Comment by crnormand** [comment]
You can use a Resource Tracker to keep track of that.   There are 4 trackers that you can define to be anything that you want.   

We wouldn't want to automatically apply such damage, since not all GMs use those rules.   

At some point down the road, we might be able to model this kind of damage (and automatically apply it), depending on what SJG says.   So until that time, I will leave this issue open.

**Comment by jhymesba** [comment]
Perhaps as a stopgap, change the 'enter DR' feature on the damage application screen from a radio button to a checkmark, so you still get the results of damage to a location, but can use your own tracked DR rather than the DR listed in the section. May have to track some things by paper.

**Comment by jhymesba** [comment]
I see that we've got the override DR feature I was looking for. It would be nice if SJGames says it's OK to automatically ablate DR, but this will work for now. 

Alternatively, make DR editable from the combat sheet, maybe using the same tricks Resources use. I'm OK with manually chewing down DR for (semi-)Ablative and Corrosive situations.

**Comment by crnormand** [comment]
Since this can now be modeled with a "damage type" Resource Tracker, I am going to close this as a feature request.
