### ISSUE TITLE
Bug: Importing GCS characters without advantages does not work

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#1984]
Version information:
![image](https://github.com/user-attachments/assets/f5ca087a-b457-4f17-8dcc-58a76d703c4d)
![image](https://github.com/user-attachments/assets/d57cd3e8-fad9-4df8-9942-5012eeadfa46)

I get the following messages when attempting to import a character who has no advantages: 
![image](https://github.com/user-attachments/assets/04ae8fbc-f97b-4cb0-ae2f-604f24fce4ef)

It seems some traits are imported, like the attributes and name, but skills and equipment and the resulting weapons are not:
![image](https://github.com/user-attachments/assets/dc25e341-bd46-4859-a394-aa86ee1a45a8)

I'm attaching two different characters I'm having this issue with. Please also check the code which handles other traits this way, maybe a similar error happens when the character has no disadvantages or skills.

[characters.zip](https://github.com/user-attachments/files/17244844/characters.zip)

**Comment by chrismaille** [comment]
Hi @Exxar, thanks for the message. The issue occurs because when the character does not have any traits the import process is interrupted and the final sheet has incomplete data.

This is the sheet after the fix:

![image](https://github.com/user-attachments/assets/5de37898-a50a-414a-ad7a-5aec363feebe)

Please let me know if this fix the issue.

**Comment by Exxar** [comment]
Yep that looks good now! Thanks!
