### ISSUE TITLE
Feature Request: Please allow mass importing of actors

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#1994]
It would be great if I could click a few buttons and have all of my custom enemies, PCs, or NPCs all in one shot.

**Comment by chrismaille** [comment]
Hi @TheFabulousIronChef , thanks for the message. My current thinking:

1. Create a button on the Actor sidebar, like the same one which exists on Compendium sidebar. Something like this:
![image](https://github.com/user-attachments/assets/4abbb547-85bc-4625-94f8-6b214c53719c)

2. Select the folder. @mjeffw, currently I'm testing the `webkitdirectory directory` [input element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory), but I'm not sure if this is the best approach (because it select all files in all subdirectories). Dialog is something like this:
![image](https://github.com/user-attachments/assets/5555b627-988f-460e-bc81-be2f88702eb9)

3. After select the folder, a new dialog will show the eligible files in that folder:
![image](https://github.com/user-attachments/assets/35d2e099-9741-454d-9169-ebeddd54992e)

Current options on import are:
* **Create**: create a new actor and import data
* **Update**: update existing actor
* **Replace**: remove current Actor, create a new one and import data

Please let me know if this helps.

**Comment by mjeffw** [comment]
I've got a solution I'll be implementing. It's the same one I use to import characters to create Doug's (Gaming Ballistic) modules for DFRPG, such as Saethor's Bane.
