### ISSUE TITLE
Feature request: /dr has an "all" option for hitlocation

### ISSUE THREAD

**Issue by Battenhatch** [crnormand/gurps#2006]
Hi all

While I'm really happy with the recent /dr chat command, I find one thing missing that would be very udeful to me: An "all" option for location, which would modify the DR in all locations at once.

**Comment by chrismaille** [comment]
Hi @Battenhatch, thanks for the message. To change DR for all locations just type the `/dr` command without locations, like `/dr +1` or `/dr !5` - more examples here: #1991

Please let me know if this helps.

**Comment by Battenhatch** [comment]
.... !

Of course! That didn't occur to me at all - thanks!!!! :D

**Comment by Battenhatch** [comment]
Now, one issue that seems to remain is adding bonus DR vs. only certain damage types, so that the split DR can be only vs. pi and cut eg. (common in High/UltraTech environments. Is that feasible under GGA or will that be a GCSGA thing?

**Comment by chrismaille** [comment]
At first, I think not, because complexity. On GGA, maybe this can be addressed creating a second command - like `/drs` - for the splitted part. 

But imagine something like `/drs +1 pi+,toxic torso,legs` - the implement it not trivial, it's too easy to create bugs, and we have fairly less use cases than original `/dr` command.

In programming, we say this is a good example of [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law). And GURPS has a _lot_ of optional rules which potentially can hit this.

**Comment by mjeffw** [comment]
@Battenhatch Please create a separate GitHub issue for adding DR bonuses for certain types of damage. I will close this issue as completed.
