### ISSUE TITLE
Request: Maneuver Menu on Combat Tracker

### ISSUE THREAD

**Issue by chrismaille** [crnormand/gurps#2027]
This feature is part of the list of improvements proposed in #2013.

The purpose is to make it easier for the GM to manage each combatant's maneuvers in the Foundry's Combat Tracker.

It's simple to use, just click on the button to select a maneuver for the combatant. To remove the selected maneuver, just right-click.

This button is visible only after that token rolled for initiative. The initiative number is now in the Token's image tooltip.

![GGAManeuverButton](https://github.com/user-attachments/assets/04cb2406-a452-4502-ac1d-8726262a9ae8)

The tooltip gives tips about the selected maneuver:
* The token's maximum movement - calculated from current move vs the selected maneuver
* Whether the token can attack
* Whether the token can defend

**Comment by jutis** [comment]
Hi
This improvement is great. I have, though, noticed some issues.
Firstly I have a question regarding why there are maneuvers called All-Out Attack, and All-Out Defense (no specific action stated). It seems that those are not needed since you have to choose a type of All-Out Attack or Defense. Just a note.

The other is something that is incorrect as far as I can see from the rules
All-Out Defense (Dodge) is the only AOD that should have a move "Half Move", the others are just "Step". See p.324 in Basic Set.

Another thing that seems to be broken is that when I choose All-Out Attack (any) the move of the character is set correctly (that is, when moving the token its ruler gets the correct movement before going red, and hoovering over the token shows the Token Tooltip Alt information correctly) but the information provided in the Combat Tracker is not correct. Even though I chose All-Out Attack (any) the Max Move shown in the Tracker says "1"

So here is the discrepancy, one by one. **Combat Tracker Icon** is the icon showed, **Combat Tracker Hoover** is the Max Move text shown when you hoover over the icon, and **Token Move** is the actual move the token can make on the map before the path shows red, and also what shows when you hoover over the token using the Token Tooltip Alt module.

- **Step Maneuvers** (Aim, Evaluate, Attack, Feint, Ready, Concentrate) - **Combat Tracker Icon:** Step; **Combat Tracker Hoover:** Max Move Step; **Token Move:** 1
- **No Move Maneuvers** (Do Nothing, Change Posture, Wait) - **Combat Tracker Icon:** Stop-sign; **Combat Tracker:** Max Move 0; **Token Move:** Seems to be Basic Move?
- **All-Out Attack Maneuvers** (undef, Determined, Double, Feint, Strong, Suppression Fire) - **Combat Tracker Icon:** Half Move; **Combat Tracker:** Max Move 1; **Token Move:** Half Move
- **All-Out Defense Maneuvers** (undef, Dodge) - **Combat Tracker Icon:** Half Move; **Combat Tracker:** Max Move 1; **Token Move:** Half Move
- **All-Out Defense Maneuvers** (Block, Parry, Double) - **Combat Tracker Icon:** Half Move; **Combat Tracker:** Max Move Step; **Token Move:** 1
- **Movement Maneuvers** (Move) - **Combat Tracker Icon:** Full Move; **Combat Tracker:** Max Move Full (digit); **Token Move:** Full Move
- **Movement Maneuvers** (Move and Attack) - **Combat Tracker Icon:** Full Move; **Combat Tracker:** Max Move Full-1 (digit); **Token Move:** (Full Move)-1

The strange effects that happens with the Movement Maneuvers, I cannot comprehend. Move and Attack is deducted 1 point of movement for the token on the map and on the Token Tooltip Alt module hoover, but also on the combat tracker Max Move. The Move maneuver only gets affected on the Token and on the Token Tooltip Alt module hoover.

I cannot say that the strange behaviors regarding Token movement and Token Tooltip Alt module hoover is not because some strange module interference, but at least they are consistent in that The token always behaves the same on the map as the Token Tooltip Alt modules shows.

**NOTE!** I have not disable any other modules that I'm using, hence the comment on the module interference in the paragraph above.

I know this was veeeeery long, but I wanted to make sure you got the correct information

br
/jimmy
