### ISSUE TITLE
Pasting Text in Journals Error

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#279]
When pasting text in journals, if you have any OtF formulas embedded therein, they will not work if there are any curly quotes or apostrophes in the rest of the journal entry. So if you have 50 clickable entries, and then put a curly quote somewhere further down in the journal entry, none of them will convert to a clickable link. Not sure if other special characters cause this, but they might. It was only the curly quotes and apostrophes that I found.

**Comment by mjeffw** [comment]
Could you leave us some text that replicates the issue?

**Comment by crnormand** [comment]
The Journal entries can cause specific problems, mainly because they embed HTML in the strings (without you knowing it).

So [+2 to hit Björn], may actually come to the parselink code as "+2 to hit&nbsp;<span style='fontsize.... "

I've done a few things to sanitize the input.
1st, we now use a Unicode encoder instead of just a Base64 encoder, so curly quotes (which are unicode) won't mess things up anymore.
2nd, we replace "&nbsp;" with a space... since we cannot (and do not want to) handle HTML in the formulas.
3rd, we strip out any html (e.g <span>Hello</span>) and just leave the enclosed text 'Hello'.

This "seems" to fix the problem(s).   But you can test when we release.
