### ISSUE TITLE
OtF formulas aren't parsed for dual damage and incendiary 

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#321]
Working with explosions last night we noticed that OtF damage formulas such as `[6d*5 inc]` or `[8d*2 cr ex]` would not get outputted as draggable damage elements. Things like `[6d*5 burn]` or dropping the `ex` from the `cr ex` made them work.

Just looks like a tweak to the pattern matching is required.

**Comment by crnormand** [comment]
Since "cr ex" is just "cr" damage (as an explosion), I can basically ignore the "ex" (and the GM can apply the explosion in other ways). 

I can set an "explosion" flag in the "action", but it will require a bit of work to update the damage chat to display it correctly and pass it on to the damage calculator.    I will start the work.... and we can finish it up sometime later.

"inc" is not a damage type (as far as the Basic Set goes).    It is a modifier on an innate attack (B433):

> Incendiary Attacks: Any attack with the Incendiary damage modifier (p. 105) does one point of burning damage in addition to its other damage; in effect, it has a one-point linked burning attack.

I was not able to find any examples of "inc" damage in the Basic Set (whereas I was able to find "cr ex" and "burn ex" damage types).   So I am disinclined to acquiesce to your request, for the moment.   However, since we can now roll multiple damages in a single chat, and drag them all onto a character, we could create the normal damage, and then add "1 burn" damage result as well.

So [2d cr inc] would create a damage chat with the results of "2d cr" in one dragable section, and "1 burn" in the second.

For the moment, I am just going to modify the parser to handle "cr ex" and "burn ex" damage types (by ignoring the "ex"), and the rest will have to wait until the platoon is better rested.   (if you can name the movies for both of my hidden quotes, I might implement this faster ;-)

**Comment by trev-dev** [comment]
The "inc" thing might just be an ultra-tech thing to describe Thermobaric grenades. By inc they must mean burn.

**Comment by mjeffw** [comment]
> Incendiary (inc)
> An Innate Attack other than a burning attack may be Incendiary. This gives the damage a secondary flame effect that can ignite volatile material (fuel, dry tinder, etc.).

The way I read this is that inc must be added as a modifier to some other damage type, like '6d imp inc'. So I agree with Chris, at this point it's just a special effect and shouldn't be listed as the damage type.

**Comment by Exxar** [comment]
There is a bunch of weapons in Ultra-Tech which have the `inc` effect in their damage type. The `inc` modifier doesn't really do anything for the damage roll itself, it just indicates that the attack is incendiary and may start fires, which is treated separate from the damage roll. So the only thing that should be done about it is parsing damage rolls including it as if it weren't there. The reason I see this as a worthwhile feature is that people are going to have weapons from UT on their characters, and this `inc` thing will be listed in their damage stats which will get automatically converted to OTFs during import. It wouldn't be nice if the system chokes on trying to roll those.

The same goes for `sur` `dkb` and `rad`.

**Comment by Exxar** [comment]
I just noticed there is knockback calculation in the ADD. `dkb` should ideally affect this.

**Comment by mjeffw** [comment]
'dkb' was implemented with #918.  The OtF damage formula now accepts any value of the form [value] [type] [modifier], where value = either a dice roll like 2d-1, type = one of the standard (11) damage types (burn, cor, cut, cr, pi, pi-, pi+, pi++, imp, tox, or fat) + 'dmg' (an unspecified type of damage), and modifier is another optional, whitespace-delimited value and is typically used for things like 'inc', 'dkb', 'nkb', and others. 

So for the examples above, the only one that wouldn't work now is @trev-dev's `[6d*5 inc]`, because 'inc' is not a valid damage type. According to Ultra-Tech, thermobaric payloads (UT155) should be written as `[6d*5 cr ex inc]`. So, Trev, change your damage formulas to match -- they are 'crushing' attacks, not 'burn'.

I'm closing this -- please open a new issue if you want specific support for a damage modifier.
