### ISSUE TITLE
[Feature Request] Create a 'catalog' of items/equipment and allow dragging/dropping onto an actor

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#328]
From @cefasheli

> Regarding the items, although it is not allowed by the foundry and we do not use all of its functionality, could be interesting to have a place so that we could put some items there and the player could copy it to their sheets.As I said in the discord, I run a campaign that needs to modify the list of equipment a lot and if I give the player the option to choose what he wants in the book this will cause problems. Maybe that place could import a GCS sheet and just show the equipment part.

This could be implemented as an Item or Journal that contains entries that can be dragged onto an actor's sheet.

The suggestion would not require full integration with the character sheet if we can add notes with the OtF formulas for weapons and attacks. For example, a Great Axe could contain the OtF formulas:

[S:"Two-Handed Axe/Mace"|DX-5|S:Axe/Mace-3|S:Polearm-4|S:"Two-Handed Flail"-4 to hit using two hands]
[SW+3 cut]

And the player can use these to roll to hit and do damage.

**Comment by crnormand** [comment]
Oh man... I love that idea.   Actually, I think we can take this a bit further.   As I mentioned in the "shopkeeper" issue https://github.com/crnormand/gurps/issues/286, each piece of equipment could also create other "things" on the character sheet.

We could build an Item editor that allows the user to fill in data for the Item (equipment), and any other "things" that the equipment might provide (melee attacks, ranged attacks, skills, etc.).    And for things that require a "Level", we could accept an On-the-Fly formula (like you described above).  That was a great idea!

The editor could look something like this (this is just a crappy mock up using a rearrangement of the current GUI to show what I mean):
![image](https://user-images.githubusercontent.com/8931036/109346062-1aa18d80-783f-11eb-821a-17da049a2cc6.png)

The GM fills in the appropriate information, and creates the Item.   Under the covers, we would create an association from the equipment to the Item, and to all of the "things" it creates, so if the equipment is removed, we can remove the Item and all of those "things".

Also, as part of the "add to character sheet" function, we will probably collapse the OtF skill formulas into the "best" answer for that character, mainly because all of the rest of the system is expecting an integer skill level in those columns.

**Comment by cefasheli** [comment]
I'm waiting for it so hard!

**Comment by mjeffw** [comment]
It is probably obvious, but this feature would be used as loot or a shop/marketplace in game.

**Comment by crnormand** [comment]
Fortunately, we have that flag already.   Equipment and Notes can be defined as "user generated" (or "don't overwrite this on import").   

By defining the Foundry Item with things like "name" "qty" "cost", etc. they may even work in generic "loot"-type modules (which deal with Items).   But in any case, they will be available in the Items tab, and the GM can assign permission to view (I believe) to hide things not yet discovered.

**Comment by cefasheli** [comment]
Suggestion, drag itens from one character sheet to another character sheet.

**Comment by Frerol** [comment]
THIS would be awesome. PLEASE, PLEASE, we need this so much :D

**Comment by crnormand** [comment]
For completeness:

The Foundry Item object is defined in the template.json, below (which I had to change... we had it in the wrong position at first... which means you must restart Foundry after you load my changes so that it reloads the template).

In Item-sheet.js, you can access the Item with 'this.object' or 'this.item' (same thing).   The only 2 attributes we need on the Item itself are 'name' and the image.   If you set the item name, i.e. this.item.name = 'bla', then you also need to set the equipment name (and any melee and ranged objects that have been created).   As I mentioned in the video, Item name == equipment name == melee attack name == ranged attack name.   But Skills, Spells and Advantages should probably have their own names.   I don't expect a lot of people to add Skills/Spells/Ads to equipment, but you never know.    Melee/Ranged/Skills/Spells should have an 'otf' atttribute, and if they do, it will be automatically collapsed when applied to an actor.   Advantages don't need one, since they don't have a 'level'.

If the otf doesn't validate, then I just don't apply it, but if you want to validate:

    if (!!parselink(otf).action) console.log('valid')

The eqt attributes below are an exact match with the Equipment class (in actor.js).  It is a single object (I didn't think Item's should hold more than one equipment).

The melee (Melee), ranged (Ranged), ads (Advantage), skills (Skill), spells (Spell) objects in the templates are "lists" (exactly how they are in our actor... they are really objects with keys like "00000", "00001").   I did this so that in the user interface, we can just use the 'name' and the 'value' attributes for input field, and it would automatically update.  

<input class="uses gcs-input-sm5" type="text" value="{{data.eqt.uses}}" name="data.eqt.uses"/>

In doing so, there is no need for a "SAVE" button, since you are editing (and updating) the live Item object.    It makes it a lot easier.

WARNING.   If you have the Furnace module installed, they created a Handlebar helper called {{count}}... which is why I added the second listener for count (and set f_count in the getData() method... so I could use {{f_count}} in the html).

As I commented in https://github.com/crnormand/gurps/issues/328 you could just steal the GCS layout, etc. and present the Item UI like that (with buttons to allow the player to add and delete) and some kind of image display, but I leave this up to you.   As you have seen, I have no fashion sense.

   ```
   {
        "eqt": {
          "name": "",
          "notes": "",
          "pageref": "",
          "count": 1,
          "weight": 0,
          "cost": 0,
          "location": "",
          "carried": true,
          "equipped": true,
          "techlevel": "",
          "categories": "",
          "legalityclass": "",
          "costsum": 0,
          "weightsum": 0,
          "uses": "",
          "maxuses": "",
          "parentuuid": "",
          "uuid": "",
          "contains": {}
        },
        "melee": {},
        "ranged": {},
        "ads": {},
        "skills": {},
        "spells": {}
      }

```
