### ISSUE TITLE
[Bug] Error while importing with containers.

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#329]
Error while importing a GCS character with containers. The attached zip file has the same character twice, once with containers, which triggered this error:

"An error occured while importing Human Guard, TypeError:Cannot read property 'carried' of undefined"

Removing the containers (the other file in the archive) fixes the issue.

[Archive.zip](https://github.com/crnormand/gurps/files/6025852/Archive.zip)

**Comment by crnormand** [comment]
The issue here is that Foundry has a hard coded limit of 10 levels of nested objects below the "Actor" level.    If a character has 4 sub-containers in Skills, it creates 11 levels (count the periods... plus 1)

data.skills.00000.contains.00000.contains.00000.contains.00000.contains.00000

We can support 3 levels of sub-containers, which have 9 levels (for ads, skills, spells) and 10 levels for equipment (since it has 2 subcategories 'carried' and 'other):
data.equipment.carried.00000.contains.00000.contains.00000.contains.00000

I've created an issue with Foundry:   https://gitlab.com/foundrynet/foundryvtt/-/issues/4679, but until then, we cannot support more than 3 levels.   

I will update the import code to provide a warning.
