### ISSUE TITLE
Weird visual error when using navigation bar

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#376]
Once you use one of the navigation buttons... it causes the GURPS icon to scroll up and off the page.

Here is what it looks like when I am running Foundry:
![image](https://user-images.githubusercontent.com/8931036/110193272-1528e200-7e01-11eb-8409-ef23678a4cc2.png)

And here is what it looks like with a player in Chrome:
![image](https://user-images.githubusercontent.com/8931036/110193263-093d2000-7e01-11eb-8f6e-cb9c96aff89d.png)

**Comment by mjeffw** [comment]
What's happening is that while trying the scroll the character sheet to display the clicked on heading, the map background is also scrolling. I have no current idea on how to fix this, as I am simply telling the DOM to "scroll this element into view".

e.g., 
```js
      var elmnt = document.getElementById(dataValue)
      elmnt.scrollIntoView()
```

This reveals that the map layer in Foundry is actually a few pixels larger that the height of the screen, otherwise it would not be scrolling as well.

**Comment by mjeffw** [comment]
Actually I found the issue and fixed it.

Code:
```js
      let target = document.getElementById(dataValue)
      let windowContent = target.closest('.window-content')

      // The '33' represents the hieght of the window title bar + a bit of margin
      // TODO: we should really look this up and use the actual values as found in the DOM.
      windowContent.scrollTop = target.offsetTop - 33
```
