### ISSUE TITLE
Problem in GCS export with attacks granted by advantages

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#379]
Ok so the use case is an iron-man type character with a bunch of different Innate Attacks. He has 3 instances of Innate Attack (Burn), an Innate Attack (Crush) and an Innate Attack (Large Pierce).

The problem lies with the 3 burning attacks. Each of those grants a separate ranged weapon with different stats, and are displayed in the GCS ranged weapon list with different notes/descriptions. Here's how it looks in GCS:
![gcs_display](https://user-images.githubusercontent.com/330181/110208886-f3277200-7e89-11eb-9db8-87b482c22d22.png)

But when I import the character into Foundry, all three of those burning attacks get the same weapon note/description so you don't know which is which until you look at the stats:
![foundry_display](https://user-images.githubusercontent.com/330181/110208902-05a1ab80-7e8a-11eb-902b-6ed256598f77.png)

As you see on the GCS screenshot, the ranged weapons in GCS inherit the notes from their advantages. In Foundry, that is not the case, and the same note, taken from one of the advantages, is displayed for all 3 weapons. Looking at the export file, I've found this:
![gca_export](https://user-images.githubusercontent.com/330181/110208975-4d283780-7e8a-11eb-8efc-cbb8ebe38a8e.png)

It seems that the GCS export groups all attacks granted by advantages which have the same name into a single attack data structure with multiple "mode" data structs, but only the top-level attack data struct has the note which is taken from the advantages, and it seems the note is taken from the first advantage with this name which is found in the gca file.

Thus, all weapons belonging to different advantages which share a name will get the same note, even though their advantages may have different notes attached to them. The desired state is that each such weapon has its own note.

My suggestion would be to not pack all of the weapons belonging to advantages with the same name into a single struct, but make one struct per advantage. YMMV, as I don't know your codebase.

I've attached the gcs and export file.
[doc_torakka.zip](https://github.com/crnormand/gurps/files/6095477/doc_torakka.zip)

**Comment by crnormand** [comment]
You may not know the story, but the import came from Fantasy Grounds.   Ronnke had made a GCA export script to feed the Ruleset in Fantasy Grounds.   I came along much later and made a GCS output template that matched that output format (xml and all).     This project started because I knew that I could read that format and create Actors in Foundry.   So that is how we started.

Fast-forward 4 months... we have learned a lot about what people do with their characters, and we have outgrown the old FantasyGrounds format.   But, we didn't rewrite everything... so our import code is still 80-85% compatible with the Fantasy Grounds format.   And this is one such case.

I've verified that GCS can export the individual notes.   I just need to tweak our import code so that it reads the notes from the correct location.   AND, I need to see if the GCA export script can do the same.

**Comment by crnormand** [comment]
And it works.    +12 Acc with Hand Lasers?!?!
![image](https://user-images.githubusercontent.com/8931036/110211396-6a4a0f80-7e64-11eb-8f80-0421b337d6f1.png)
I'm going to check the GCA export and close this issue.

**Comment by Exxar** [comment]
Yep I just took the laser rifle stats from Ultra-Tech :D

Thanks a bunch!
