### ISSUE TITLE
[Feature Request] Configuration for default names of resource trackers

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#380]
I'm using Fantastic Dungeon Grappling which introduces a new resource to combat, Control Points. It's the grappling analog to hit points - when grappling you roll control point damage and apply it to your target. Currently, I have to manually rename the first resource tracker on every actor to "Control Points". Would it be possible to add a configuration setting where you could define the default names of all four resource trackers for new actors?

**Comment by crnormand** [comment]
No, it is definitely not possible... well... actually now that you mention it, that might be possible.  :-)

And a good idea.   Thank you!

**Comment by Exxar** [comment]
:D

**Comment by mjeffw** [comment]
I'm about to continue a DF campaign that also uses FDG. This would help me too! Plus I can add multiple, custom thresholds for 2xCM, 1.5xCM, etc. 

I'll plan to add this to the next release.

**Comment by mjeffw** [comment]
Step one is complete: you can create custom thresholds in a resource tracker. On the full sheet, edit a tracker and you'll get this window:

![image](https://user-images.githubusercontent.com/7349413/110999369-426c1780-834e-11eb-9db7-95270120770d.jpeg)

Fill out the name, Max, min, and value as usual. In the section titled "Thresholds:" click the plus button:

![image](https://user-images.githubusercontent.com/7349413/110999576-9414a200-834e-11eb-966a-249237553feb.jpeg)

Add the boundary of a "threshold" for this resource. For FDG this will be Control Maximum, and the first threshold is 1/10 CM. So any control points less than 1/10 of your total CM means there's no DX penalty. Let's call this "Normal". In the resource tracker editor, you have to set based on the maximum value, so this would be CM x 0.9. We'll give this a green color. 

The next threshold happens when your control points are less than or equal to CMx0.9 but greater than CMx0.5. We'll call this "Grabbed". 

Repeat for all the other thresholds and you'll end up with this:  

![image](https://user-images.githubusercontent.com/7349413/111000314-d1c5fa80-834f-11eb-842a-1f921b9b9a2c.jpeg)

Click update to save these changes, and now the tracker will not only display your current amount of control points, it will show the named condition and color as well. You even get the tool tip functionality. 

![image](https://user-images.githubusercontent.com/7349413/111000558-3ed99000-8350-11eb-90ae-c52a8656be89.jpeg)

My next step will be to give the GM an editor that will set this  data on every actor.

**Comment by mjeffw** [comment]
BTW, I worked with Doug Cole to get those threshold names.

**Comment by Exxar** [comment]
Yeah I saw you chatting with Doug on his discord. This is awesome! And one of the best things is that you can set whichever comparison operator you want, because for example HP and FP thresholds are "more than half HP" while for FDG it is "half or more".

**Comment by mjeffw** [comment]
You can (in the next release) define standard resource trackers for your world, and optionally add those trackers to imported characters. 

blob:null/0df53add-2af0-4677-960c-40a704636b3c

**Comment by Exxar** [comment]
Awesome!
