### ISSUE TITLE
[Bug] The "Count" field is overwritten to "False" value after opening any item

### ISSUE THREAD

**Issue by WeirdBread** [crnormand/gurps#467]
If one tries to open an item, the "Count" field will be overwritten to "False" value no matter what actual data was there before. Thus if one opens any items and updates without touching the "Count" field their item's counter will be set to "0"

![изображение](https://user-images.githubusercontent.com/79375204/113145708-70e75f00-9237-11eb-8f9a-27b56bc0e788.png)

**Comment by crnormand** [comment]
Wow, I do not see this behavior at all.   Can you attach the .gcs or .gca4 character so I can see if I can recreate this issue?

Also, are you using the latest release of our code 0.8.21?

**Comment by WeirdBread** [comment]
The bug with compatibility was confirmed by Discord user LordHelmet. 

![изображение](https://user-images.githubusercontent.com/79375204/113295060-604eeb80-9300-11eb-8361-ac673e5b0923.png)

**Comment by crnormand** [comment]
Found it... and it is fixed (in the next release).  The Furnace makes the assumption that no one in their right mind would ever use `{{count}}` in their HTML, say like, for referring to the 'count' variable in an equipment object!    They overwrote `{{count}}` to be some kind of handlebar helper... which is returning 'false'. 

So when we filled the initial value of the input field using:

`   <input class="count gcs-input-sm5" type="text" value="{{count}}" data-dtype="Number" />`

You got their fancy shmancy handlebar helper, and not the instance variable.

It is fixed in the next release.
