### ISSUE TITLE
Conditions with timer.

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#490]
I would to to suggest some conditions working with a timer, For example: the guy take damage and get shocked until the next turn, so at the start of their round the conditions reset. Another example: the guys need 2 turns to prepare a bow or reload ammo so you can set the numbers of rounds and it start a counter. There's a module called utility Belt that does it but does,t work for us.

**Comment by crnormand** [comment]
We have every intention on doing this.    Foundry calls these "Active effects", and one of their main features is a "duration". 
However, we are waiting to see how far SJG will let us go with this level of automation.     

Since this has been discussed many times before, I am going to close this issue.  If SJG games allows us to provide this level of automation... we will implement it almost immediately ;-)
