### ISSUE TITLE
Weapons that are both thrown and melee don't import correctly from GCA

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#509]
When importing characters exported from GCA, it seems that Foundry only discovers the thrown mode and not the melee mode on any weapon which has both modes. I tried this first with the Hatchet, then the Throwing Axe, then the Spear. It seems to be consistent in all cases.

Thanks for your work.

**Comment by crnormand** [comment]
That is truly odd because I fixed this problem a few releases ago, using Spear as an example.

Can you attach a gca4 file that is exhibiting this issue?    I assume you are using the latest export script (available here: https://drive.google.com/file/d/1vbDb9WtYQiZI78Pwa_TlEvYpJnR_S67B/view?usp=sharing)?

**Comment by engurrand** [comment]
My bad. I missed your update to the export script. Sorry for the unnecessary bug report, thank you for fixing it, and thanks again for your work on this program. It's over here changing our lives.
