### ISSUE TITLE
[Feature Request] Give imported Equipment the save during import checkbox

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#579]
In my campaign the players use a lot of consumables, torches, arrows, lamp oil, you name it.
After they used it they reduce the quantity on the character sheet.
And than, more often then not, I re-import their character overwriting all their gear and replenishing all their consumables.

So it would be nice to have the same checkbox on imported equipment like on the equipment made in foundry to keep it during imports.

This would make it easy to create equipment quickly be using ready made lists in GCS / GCA but prevent it from being overwritten during imports.

**Comment by crnormand** [comment]
This gets tough.    The current user generated equipment works because it doesn't already exist in the import, and therefore, it is easy to copy over from the old list to the new list.

We would have to build in some logic to match up the equipment name (and probably path as well, since there is no limitation that equipment names be unique).

For example:

Backpack -> 5 Healing potions
Belt -> 1 Healing potion

And if the user happens to move the equipment around (which they can by dragging and dropping), we would lose its position.   

Although, GCS recently changed their IDs system to be some kind of global ID, so we could probably use that instead of a name/path, but GCA doesn't have anything like that.   Their ID seems to be a simple integer count, which means that on subsequent exports/imports, the IDs might change?  Or might be reused?   I am not certain.

Of course, this is a good idea, and I will keep churning on it.   BTW, another user encountered the same issue, and deleted the consumables from GCS and manually created them in Foundry, and as such, they survive the import.

**Comment by crnormand** [comment]
Oh man, are you going to LOVE me!   

GCA/GCS equipment now has a flag on the editor:

![image](https://user-images.githubusercontent.com/8931036/120695465-6cc70000-c479-11eb-8d99-7ae047e46c1e.png)

And if it is checked, it will display in the equipment list with a checkered flag:

![image](https://user-images.githubusercontent.com/8931036/120695628-9aac4480-c479-11eb-83d7-69949a577788.png)

And when this flag is showing, that equipment will ignore QTY/Count/Uses and MaxUses updates from the import.

Also, equipment now remembers where it was in the inventory, and trys to put itself back in the same (or similar) location.   

NOTE:   If you ever want to get the imported value, you can either turn that flag back off, or you can just DELETE the equipment on the character sheet and it will automatically be recreated.
