### ISSUE TITLE
Modifier Bucket editor not centered

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#585]
I know it is "EXPERIMENTAL", but the different scale factors have the editor off center and low (it is covering up some of the macros and the bucket).  
I tried looking at tooltip-window.js activateListeners(html), but I wasn't sure exactly how to make it fit (I can do the math, of course, but I wasn't sure what value to set... my lack of html/css still biting me in the butt).

100%:
![image](https://user-images.githubusercontent.com/8931036/117358365-123f8180-ae84-11eb-8e33-6a4b0fc4a8e0.png)

80%:
![image](https://user-images.githubusercontent.com/8931036/117358448-297e6f00-ae84-11eb-9e25-beaab46129f2.png)

90%:
![image](https://user-images.githubusercontent.com/8931036/117358513-4155f300-ae84-11eb-8fe1-c45078eea9b3.png)

110%:
![image](https://user-images.githubusercontent.com/8931036/117358588-56cb1d00-ae84-11eb-9f0c-41471a5ddd0e.png)

120%:
![image](https://user-images.githubusercontent.com/8931036/117358733-81b57100-ae84-11eb-9988-fbce968580e5.png)

**Comment by mjeffw** [comment]
I don't see that same behavior, except for horizontal centering -- it shifts to the left if small, and right if larger. That makes sense because I didn't adjust the horizontal spacing for the new width. But it always appears above the modifier bucket for me. (AKA, it works on my machine!)

Is there anything else off with the popup window -- like, do any of the buttons wrap?
