### ISSUE TITLE
Modifier Bucket window is 'wobbly'

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#598]
During mouse-over the bucket modifier is 'wobbly' which sometimes makes it hard to click the right spot.
Using the latest Chrome browser.

https://user-images.githubusercontent.com/80178910/117552350-1964bc00-b04b-11eb-89d5-3be5897a685a.mp4

**Comment by Legendsmith** [comment]
This looks like a CSS/layout issue.

**Comment by crnormand** [comment]
Yes, it seems the translations are larger than the original text, and the buttons are moving because of it. When a button hits focus, it grows just a little bit, I think the font gets bigger, I can't remember everything, but the idea was to show that it is "in focus".

￼The individual buttons are ￼not actually "wobbly" because if you stay on a button it will stay expanded, it'll just push the other buttons down. Of course it it depends on what your definition of wobbly is :-)

￼ there really isn't a great solution for this. We can make the modifier bucket area larger, so that hopefully translations fit better. Or you can change the translation to use abbreviations, if possible.￼

**Comment by Legendsmith** [comment]
Actually @crnormand I think there might be another solution that works just fine, that doesn't involve changing the modifier bucket's size. Set the hover mode of these  tooltips to have an overflow value of hidden. ``overflow:hidden;`` This will just clip off the slightly larger edge, but that's fine.

**Comment by mjeffw** [comment]
Does it work this way for everyone? On my machine, the buttons do not change size when hovering. I especially coded the CSS not to change size.
