### ISSUE TITLE
Player's HP/FP Was Overwritten Without Prompt When Import

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#724]
I have one of my player reported that everytime he imports, it never asks for overwrite prompt, I have other players reported it as well but very rarely but this particular player is as unlucky as his dice rolls.

**Comment by crnormand** [comment]
I don't know what to say.   There is basically no way this should happen.  The configuration setting is controlled by the GM, so there is no way that they should be able to override it.

Is that player using Chrome?   One of our other users encountered the weirdest error that I could not reproduce... and it turned out they were using the Brave browser (which is based on Chrome, but isn't Chrome).   Switching to Chrome fixed their problem.

Other than that, I have no ideas.   You could try turning the setting off and on, to force an update, but I don't see how one client could have a different value than the GM.
