### ISSUE TITLE
GCA Export: Items with weight less than 1 lb. have their weight divided by the count if quantity is greater than one

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#873]
Another one for the GCA item export (sorry! this should be the last one until my group actually plays and gets some loot, at least...). 

If an item weighs less than 1 pound (rations, for instance), it exports normally and keeps the appropriate weight if there are only one of them. However, if the quantity is more than one, the weight type="number" in the export file appears to be divided by the count, instead of remaining constant to then be multiplied for the weightsum. So, 1 ration weighs 0.5 lbs., but a stack of 5 rations weigh 0.1 lbs. each. 

Here's what it looks like when imported:

![GCASmallItemWeight](https://user-images.githubusercontent.com/85463974/125033159-d079b580-e043-11eb-8dbd-30b5b2571e94.PNG)
(The 100 count copper farthing row is abbreviating the 0.00016 weight)

This happens with every item I've tried that has a base weight less than 1 in GCA—rations, arrows, crossbow bolts, copper coins, etc.

Here are the export file and the GCA character file:
[TestCharacter.gca4.TXT](https://github.com/crnormand/gurps/files/6789229/TestCharacter.gca4.TXT)
[TestCharacter.zip](https://github.com/crnormand/gurps/files/6789231/TestCharacter.zip)

**Comment by crnormand** [comment]
No worries!   We really appreciate it when our players help us fix bugs.

Fortunately, this bug has been fixed already!    It was caused by the same issue that caused https://github.com/crnormand/gurps/issues/864

![image](https://user-images.githubusercontent.com/8931036/125082440-380c2100-e095-11eb-9fc3-51e873fed592.png)

So it will be available in the next release.
