### ISSUE TITLE
Physical Dice issues

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#896]
If the user executes` /r 3d20 `or` /r [3d20] `when Physical Dice is turned on, the dialog doesn't display the dice terms (because it is using Die, not GurpsDie), and an exception is thrown when the editor tries to validate the rolls.

Not a high priority, since D6 is the primary dice for GURPS... but we do have people that roll non-D6... the question then becomes, would they also be using Physical Dice? ;-)

**Comment by crnormand** [comment]
Combat initiative does not use the Physical Dice for the final 1d6 roll (to break initiative ties)

**Comment by mjeffw** [comment]
I got it (kinda) working.

In my next PR, you can enter almost any kind of roll and it will work with the Physical Dice feature.

The one exception I have found (so far) is entering a die roll without a leading number, such as d20, or d12. For some stupid reason, those RollTerms do not resolve to DiceTerms (i.e., Die), but instead to StringTerm. When the StringTerm is evaluated, then it is converted to a Die and rolled. Unfortunately that is deep in the code and I don't yet have a solution for it.

**Comment by mjeffw** [comment]
Okay, one more step forward:

I now have Physical Dice working for chat rolls that do not start with a number, e.g., `/r d20`.  

For the moment, the only place that I see that is missing is the initiative roll. Changing this will involve changing code in Foundry's `Combatant.getInitiativeRoll()`. The changes involve making that function async, which will affect two other locations in the code: `Combatant.rollInitiative()` and 'Combat.rollInitiative()`. Those two locations will have to be able to `await` the call to getInitiativeRoll() in order to consume the results. The call in `Combat` is already async and therefore easy to change to await the results, but the call from `Combatant.rollInitiative()` is not async, and I'm afraid what chain reaction of code changes in the base Foundry that would cause.
