### ISSUE TITLE
Token-based targeting

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#940]
Foundry's implementation of targets is user-based -- i.e., the user is targeting one or more tokens. That doesn't help the user with multiple tokens -- typically the GM -- track which of his tokens is targeting another token in the scene. 

I would like the ability to track targets by token, so when Grend is being specifically targeted by the Wraith and She is being targeted by the Draug, that information is both saved and visible in the UI, and could be used by the system for various things. For example, we could calculate range between targeter and targetee and automatically apply range penalties.

**Comment by crnormand** [comment]
I see what you mean.   We could remember the LastActor's last target, and when that actor becomes active again, it would select the last target.   If the GM changes the target, we would record it in the actor (or token?).

I think we have to do this on a Token basis... because of the whole synthetic actor issue.    But each token could remember their target selection, and when that token's actor becomes the "active" actor, it automatically selects the token's target.     Hmmm.. but that could trigger all of the tokens for that Actor.    We may need to keep a "GURPS.LastToken" variable as well.

**Comment by Volksters** [comment]
I would be up for players targeting the token and being able to roll distance based on the map's grid size and relative positions. Partly because this reduce the amount of "Why is my target only 2 on First Aid Skill after I rolled? Oh, I accidentally had my drag ruler on and it added to my modifier. Umm, GM, what was I supposed to roll again? What was my modifier?"

**Comment by crnormand** [comment]
I am going to close this because there are is a module that does this work:  Target Recall
https://foundryvtt.com/packages/target-recall
