### ISSUE TITLE
[FEATURE REQUEST] Chat/OTF Command to Set Resource Trackers

### ISSUE THREAD

**Issue by Snailramp** [crnormand/gurps#941]
We use Resource Trackers for firearm ammo, and it would be awesome if there could be a way to set Resource Tracker parameters through OTF commands.  My thought was to be able to have a OTF formula/button on a item that when activated, would populate a designated Resource Tracker with the correct settings.

Thank you very much for your time.

**Comment by crnormand** [comment]
You mean the MIN, MAX and progression parameters?    Sorry, we don't have plans for that.   The GM can create trackers using the system settings, and individual players can assign them to their character sheet.   Since this doesn't seem like a process that would be duplicated a lot (once you have defined an "Ammo" tracker, do you need to define another one?   The only real change might be the MAX value... but once that is set, would it be changed often enough to warrant a chat command?

I am going to close this issue (for the moment), but I am misunderstanding something, please comment, and I will re-open.
