### ISSUE TITLE
Lag Issue When Reaching A Number Of Items In Character Sheet

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#958]
I decided to ditch the GCS item sheet and opt for the item compendium. My characters have an average of 40-50 items, mixture of miscellaneous and weapons/armour, I noticed significant lag issues when moving items around or when item is shifting into a container.

**Comment by crnormand** [comment]
I made a few changes in 0.11.8 that sped up the updates of character sheets (with lots of Items).    It still isn't instantaneous, but a 20 second update went down to 2 seconds (with about 50 items).

We plan to rewrite the Item "bonuses" code to use ActiveEffects (instead of my "homegrown" update system), and hopefully, this will reduce the extra forced updates (which are the main cause of the delay) to zero.

I am going to close this issue (for now), and we can re-open it, if the ActiveEffects rewrite doesn't work as planned.
